name: root_app

packages:
  - core/
  - movie_db_app/

scripts:
  build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner across all packages.
    packageFilters:
      dependsOn: build_runner
      ignore: "core"

  build_runner_core:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: "*core*"
    description: Run build_runner in the core package
